export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MSG = 'CHANGE_MSG';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';


